### ISSUE TITLE
I dont think I belong here

### ISSUE THREAD

**Issue by AdamxzV3** [ClaraCrazy/ClaraCrazy#1]
<p align="center">
  <img src="https://user-images.githubusercontent.com/49810075/228370366-551e8e73-04e7-470b-9de7-3652654f76c7.png" width="800"/>

```c
furi_log_i(furi_hal_version_do_i_belong_here);

>>> false
```
<p align="center"> <em>breaks</em>

**Comment by ClaraCrazy** [comment]
?

**Comment by ClaraCrazy** [comment]
Are ever going to elaborate on that, @AdamxzV3 ?

**Comment by AdamxzV3** [comment]
yes

**Comment by ClaraCrazy** [comment]
> yes

when?

**Comment by ClaraCrazy** [comment]
much better - closed as completed.
